# update_s3_htmls job
  update_s3_htmls:
    machine:
      image: ubuntu-1604:201903-01
    steps:
    - run:
        <<: *setup_linux_system_environment
    - run:
        <<: *binary_populate_env
    - run:
        <<: *binary_checkout
    - run:
        name: Update s3 htmls
        no_output_timeout: "1h"
        command: |
          echo "declare -x \"AWS_ACCESS_KEY_ID=${PYTORCH_BINARY_AWS_ACCESS_KEY_ID}\"" >> /home/circleci/project/env
          echo "declare -x \"AWS_SECRET_ACCESS_KEY=${PYTORCH_BINARY_AWS_SECRET_ACCESS_KEY}\"" >> /home/circleci/project/env
          source /home/circleci/project/env
          set -ex
          retry pip install awscli==1.6
          "$BUILDER_ROOT/cron/update_s3_htmls.sh"



